export const buttonsArr = [
  { value: "c" },
  { value: "+-" },
  { value: "%" },
  { value: "/" },
  { value: "7" },
  { value: "8" },
  { value: "9" },
  { value: "X" },
  { value: "4" },
  { value: "5" },
  { value: "6" },
  { value: "-" },
  { value: "1" },
  { value: "2" },
  { value: "3" },
  { value: "+" },
  { value: "0" },
  { value: "." },
  { value: "=" },
];
